# Generated by Django 6.0.4 on 2026-05-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lessontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='repeat_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule_type',
            field=models.CharField(choices=[('single', 'Один урок'), ('recurring', 'Повторюваний урок')], default='single', max_length=20),
        ),
    ]
